language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12
  - env: JDK=adoptopenjdk11-openj9
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
  - env: JDK=amazon-corretto-11
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://d3pxv6yz143wms.cloudfront.net/11.0.4.11.1/amazon-corretto-11.0.4.11.1-linux-x64.tar.gz'
  - env: JDK=graalvm-ce-19.1.1
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-linux-amd64-19.1.1.tar.gz'
