language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk11
  - jdk: openjdk14
  - env: JDK=adoptopenjdk11-openj9
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
  - env: JDK=amazon-corretto-11
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz'
  - env: JDK=graalvm-ce-20.1.0
    before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    - source ./install-jdk.sh --url 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz'
